DRAFT: Add support for dockerfile frontend `add-hosts` option
vito/oci-build-task pull request #24
Opened 2020-03-31 04:25 UTC by bradfordboyle

2020-03-31 04:26 UTC, bradfordboyle commented
This is a first pass at addressing #23. Still need to figure out how to run tests.

2021-01-06 15:23 UTC, vito requested changes
Thanks for working on this! Sorry for the slow turnaround. If you're still interested in working on this, there are better [contributing docs](https://github.com/vito/oci-build-task/blob/master/CONTRIBUTING.md) now, and tests auto-run for PRs now too.

2021-01-06 15:23 UTC, vito commented on types.go
> +	AddHosts string `json:"add_hosts" envconfig:"ADD_HOSTS,optional"`
Since this is a Buildkit-specific feature, can this be called `BUILDKIT_ADD_HOSTS`?

2021-01-20 15:35 UTC, vito approved these changes
lgtm - thanks!

could use a README update but I can add that myself prior to shipping

2021-01-20 15:35 UTC, merged